"""
Django settings for dataviz project.

Generated by 'django-admin startproject' using Django 2.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
# Add for translation
from django.utils.translation import ugettext_lazy as _

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '----------------------------------------'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['---------', 'localhost']

#Add by Chokki to change the user behavior
AUTH_USER_MODEL = 'accounts.User'

# Application definition

INSTALLED_APPS = [
    'jet.dashboard', # for django-admin design
    'jet', # for django-admin design
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Add Apps
    'accounts',
    'visualizations',
    'frontend',
    'modeltranslation',
    'rosetta',  # NEW
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'crum.CurrentRequestUserMiddleware', # for getting current user https://django-crum.readthedocs.io/en/latest/
    'ipinfo_django.middleware.IPinfo',
]

ROOT_URLCONF = 'dataviz.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
            ],
        },
    },
]

WSGI_APPLICATION = 'dataviz.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': '------------',
        'USER': '---------',
        'PASSWORD': '------------',
        'HOST': 'localhost',
        'PORT': '5432'
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/
LANGUAGES = (
    ('en', _('English')),
    ('fr', _('Français'))
)
MODELTRANSLATION_DEFAULT_LANGUAGE = 'en'
MODELTRANSLATION_FALLBACK_LANGUAGES = {'default': ('en', 'fr'), 'fr': ('en',)}
MODELTRANSLATION_PREPOPULATE_LANGUAGE = 'en'

LANGUAGE_CODE = 'en'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Contains the path list where Django should look into for django.po files for all supported languages
LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'locales'),
)


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, "static/")
STATICFILES_DIRS = [
    os.path.join(BASE_DIR,'assets')
]

MEDIA_URL = '/files/'
MEDIA_ROOT = os.path.join(BASE_DIR,'files')
COUNTRY_JSON = os.path.join(BASE_DIR, "files/static/country.json")
COUNTRY_FR_JSON = os.path.join(BASE_DIR, "files/static/country_fr.json")
COUNTRY_INIT_FR_JSON = os.path.join(BASE_DIR, "files/static/country_init_fr.json")
DF_FILES = "/dfs/"
UPLOAD_FILES = "/uploads/"
DEFAULT_FILE_SAVE = ".csv"

# Email settings
EMAIL_HOST = '---------'
EMAIL_HOST_USER = '---------'
EMAIL_HOST_PASSWORD = '---------'
EMAIL_PORT = '587'
EMAIL_FROM = '---------'
EMAIL_RECEIVERS = ['---------', '---------']
EMAIL_SUBJECT = 'ODEON Feedback'
SUBJECT_SHARE = "Share Information from ODEON"

# To solve the problem of popup denied on django jet dashboard
X_FRAME_OPTIONS = 'SAMEORIGIN'
PREFIX_FILE = 'f'
PREFIX_PROJECT = 'p'
PREFIX_DASH = 'd'
PREFIX_TRANSPROJECT = 't'
LIST_EXTENSIONS = ['csv','json','xls','xlsx']
HEIGHT_PLOT = 600
TIMEOUT_CACHE = 3000
DEFAULT_DATATYPE = 5
MAX_UPLOAD_FILE = 2e8
NON_EXPERT = 'non-expert'
EXPERT = 'expert'
INTERMEDIATE = 'intermediate'
NEW_DATATYPE_RULE = '''
if df[col].dtype.name == "datatype_name" and col.lower() == str("column_name").lower():
   result = True
'''
OPPOSITE_DATATYPE_RULE = '''
if df[col].dtype.name == "datatype_name" and col.lower() == str("column_name").lower():
   result = False
'''
MEASURES_TYPES = ["numerical"]
ICON_NUM = "plus_one"
ALL_TYPES = ["numerical", "temporal", "geographical", "categorical"]
VIZ_X = "1"
VIZ_Y = "2"
VIZ_COLOR = "3"
VIZ_FACET_COLUMN = "9"
VIZ_FACET_ROW = "8"
VIZ_ANIMATION = "11"
VIZ_SHAPE = "4"
VIZ_SIZE = "5"
VIZ_LABEL = "6"
VIZ_HIERACHY = "10"
VIZ_ORIENTATION = "7"
VIZ_GROUPING = "12"

VIZ_MARKER_OFFSET = 0.04
DATE_FORMAT = {
    'valexact': 'YYYY-MM-DD HH24:MI:SS',
    'y': 'YYYY',
    'ym': 'YYYY-MM',
    'ymd': 'YYYY-MM-DD',
    'hi': 'HH24:MI'
}
MAPBOX_TOKEN = '---------'
MAX_SCORE = 11
BAD_VIZ_SCORE = "0"
OPTION_SCORE_NUM = {
    '1': "equalto",
    '12': "lessequalthan",
    '13': "lessequalthan",
    '14': "lessequalthan",
    '2': "equalto",
    '3': "equalto",
    '4': "equalto",
    '5': "equalto",
    '6': "equalto",
    '7': "equalto",
    '9': "greaterequalthan"
}
DEFAULT_OPTION_SCORE_NUM = "equalto"
OPTION_SCORE_TRUE = "istrue"
OPTION_SCORE_FALSE = "isfalse"
OPERATOR_CORRESPONDANTS = {
    "equalto": "==",
    "notequalto": "!=",
    "greaterthan": ">",
    "lessthan": "<",
    "greaterequalthan": ">=",
    "lessequalthan": "<=",
    "istrue": "is True",
    "isfalse": "is False"
}
MAX_UNIQUE = 100
MAX_THRESHOLD = 0.8
MAX_THRESHOLD_NUM = 0.03
WEIGHT_EXPERT = 80
WEIGHT_INTERMEDIATE = 0
WEIGHT_NON_EXPERT = 20
MIN_SCORE_THRESHOLD = 0
DATA_UPLOAD_MAX_MEMORY_SIZE = 5242880
COLORS_PLOT = [
    '#1f77b4',  # muted blue
    '#d62728',  # brick red
    '#2ca02c',  # cooked asparagus green
    '#9467bd',  # muted purple
    '#bcbd22',  # curry yellow-green
    '#17becf'   # blue-teal
    '#ff7f0e',  # safety orange
    '#8c564b',  # chestnut brown
    '#e377c2',  # raspberry yogurt pink
    '#7f7f7f',  # middle gray
]
NOT_SUPPORTED_AVG = [13,17,19,20]
GRAPH_HISTOGRAM = 3
GRAPH_BAR = 10
GRAPH_LOLLIPOP = 15
FEATURE_HAS_BINNED = 15
DEFAULT_AGG = "max"
DEFAULT_DATE_DIM = "ym"
DEFAULT_BINS = 10
GOOD_CORR = 0.5
VERY_GOOD_CORR = 2.0
MAX_DISTINCT_CAT = 7 # Use for color bubble
MAX_DISTINCT_CAT_TEMP = 10
DINSTICT_CAT_FACET = 500   #12 (Change to 12 later)
GOOD_CAT_DATATYPES = [1,3]
MAP_VIZ = [11, 16]
LAT_DATATYPE = 7
LON_DATATYPE = 9
SHAPE_DATATYPE = 8
POINT_DATATYPE = 10
LIST_AGG = ["avg", "avg"]   #["sum", "avg"]
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10240
MAX_VIZ_SHOWN = 10
#New variables
EXPORT_ODP_FORMAT = "csv"
DELIMITER_ODP = "%3B"
SUFFIX_DUPLICATE_COL = "_1"
ZOOM_MAP = 7
SIZE_MAP = 20
NB_ROWS = 10
DATATYPE_INT = '4'
MAX_PROJECTS_PAGE = 12
MAX_DATA_PAGE = 12
MAX_ITEMS_HOME_PAGE = 5
WEIGHT_COMPLETE_DATA = 1.0
WEIGHT_COLUMN_LABELS = 1.0
WEIGHT_COLUMN_DESCRIPTIONS = 1.0
WEIGHT_DATA_INFO = 1.0
REFRESH_TIMEOUT_UNIT = "s"
EXPLORE_COLUMN_DATATYPES = [1,2,3,4]
DEFAULT_PROJECT_IMAGE = "/static/images/nopreview.jpg"
SETUP_DASH = {"shviztit_nov": True, "shviztit_less": False, "shviztit_adv": False,
"shvizdes_nov": True, "shvizdes_less": True, "shvizdes_adv": True,
"shvizmark_nov": False, "shvizmark_less": True, "shvizmark_adv": True,
"shdtsource_nov": True, "shdtsource_less": True, "shdtsource_adv": True,
"shcstmen_nov": True, "shcstmen_less": True, "shcstmen_adv": True,
"shfilt_nov": True, "shfilt_less": True, "shfilt_adv": True, "shdsp_typ": False}
FEEDBACK_TYPES = {"general": 'General', "status": 'Project Status', "data": 'Data Issue', "requirement": 'Requirement Clarification'}
PROJECT_TYPES = {"external": 'OGD Reuse', "internal": 'OGD Reuse', "proposed": 'Suggested Project'}
USER_REQUEST_TYPES = {"citizen": 'Citizen', "developer": 'Developer'}
USER_TYPES = {"non-expert": "Citizen", "intermediate":"Publisher", "expert":"Developer"}
ISSUE_TYPES = [
    ('ERD', 'Erroneous data'),
    ('MISD', 'Missing data'),
    ('DWWV', 'Data with a wrong value'),
    ('CDNU', 'Coded data not understandable'),
    ('OBSD', 'Obsolete data'),
    ('OTHD', 'Other Issue')
]
MAX_WORDCLOUD_ITEMS = 100
DEFAULT_COUNTRY = "Belgium"
#New
EMAIL_SUBJECT_PROTO = 'ODE Feedback'
LIMIT_HOME_MOBILE_POP = 6
LIMIT_HOME_MOBILE_NEW = 3
LIMIT_HOME_MOBILE_THEMES = 4
CHECK_SHOW_IN_APPS = False
MOBILE_APP_LANG = "fr"
IPINFO_TOKEN = 'fed2de602f46bb'
REUSES_FR = os.path.join(BASE_DIR, "files/static/reuses_odfrance.csv")
THEME_REUSES_FR = 10
STATUS_REUSES_FR = 3
DATASET_LINK_FR = "https://www.data.gouv.fr/fr/datasets/"
URL_IFRAME = "http://localhost:8000/embed/#dash_code#/#viz_code#/"
URL_DASH_IFRAME = "http://localhost:8000/dashboard/#dash_code#/"
RELOAD_TIMEOUT = 4 # in days
DEFAULT_THEME_ID = 10
SKIP_THEMES = []
VERSION = 3
