# Generated by Django 2.2.10 on 2020-06-02 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'DataType',
                'verbose_name_plural': 'DataTypes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(blank=True, max_length=5, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('formula', models.TextField()),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='VizInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'verbose_name': 'VizInput',
                'verbose_name_plural': 'VizInputs',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='VizMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'VizMark',
                'verbose_name_plural': 'VizMarks',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VizType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='viztypes/')),
            ],
            options={
                'verbose_name': 'VizType',
                'verbose_name_plural': 'VizTypes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VizTypeMarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.TextField()),
                ('user_type', models.CharField(choices=[('expert', 'Expert'), ('intermediate', 'Intermediate'), ('non-expert', 'Non Expert')], default='non-expert', max_length=30)),
                ('vizmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viztypemarks', to='visualizations.VizMark')),
                ('viztype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viztypemarks', to='visualizations.VizType')),
            ],
            options={
                'verbose_name': 'VizMarkRule',
                'verbose_name_plural': 'VizMarkRules',
                'ordering': ['user_type'],
            },
        ),
        migrations.CreateModel(
            name='VizOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('user_type', models.CharField(choices=[('expert', 'Expert'), ('intermediate', 'Intermediate'), ('non-expert', 'Non Expert')], default='non-expert', max_length=30)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vizoutputs', to=settings.AUTH_USER_MODEL)),
                ('vizinput', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vizoutputs', to='visualizations.VizInput')),
                ('viztype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vizoutputs', to='visualizations.VizType')),
            ],
            options={
                'verbose_name': 'VizOutput',
                'verbose_name_plural': 'VizOutputs',
                'ordering': ['user_type'],
            },
        ),
        migrations.CreateModel(
            name='VizInputFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vizinputfeatures', to='visualizations.Feature')),
                ('vizinput', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vizinputfeatures', to='visualizations.VizInput')),
            ],
            options={
                'verbose_name': 'VizInputFeature',
                'verbose_name_plural': 'VizInputFeatures',
            },
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, editable=False, max_length=8)),
                ('url', models.CharField(blank=True, max_length=250)),
                ('file_name', models.FileField(blank=True, upload_to='')),
                ('title', models.CharField(max_length=250)),
                ('default_settings', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploadfiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
            },
        ),
        migrations.CreateModel(
            name='FileSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perso_settings', models.TextField(blank=True, null=True)),
                ('uploadfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filesettings', to='visualizations.UploadFile')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filesettings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FileSetting',
                'verbose_name_plural': 'FileSettings',
            },
        ),
        migrations.CreateModel(
            name='DataTypeRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regular_expression', models.TextField()),
                ('user_type', models.CharField(choices=[('expert', 'Expert'), ('intermediate', 'Intermediate'), ('non-expert', 'Non Expert')], default='non-expert', max_length=30)),
                ('datatype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datatyperules', to='visualizations.DataType')),
            ],
            options={
                'verbose_name': 'DataTypeRule',
                'verbose_name_plural': 'DataTypeRules',
                'ordering': ['user_type'],
            },
        ),
    ]
