# Generated by Django 2.2.10 on 2020-06-02 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VizInputFeatures',
            new_name='VizInputFeature',
        ),
        migrations.RenameModel(
            old_name='VizTypeMarks',
            new_name='VizTypeMark',
        ),
    ]
