# Generated by Django 2.2.10 on 2020-06-04 13:35

from django.db import migrations, models
import visualizations.models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0002_auto_20200602_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesetting',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=8),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='file_name',
            field=models.FileField(blank=True, null=True, upload_to=visualizations.models.path_and_rename),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
