# Generated by Django 2.2.10 on 2020-06-09 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visualizations', '0004_auto_20200604_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, editable=False, max_length=8)),
                ('project_settings', models.TextField(blank=True, null=True)),
                ('project_history', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.RemoveField(
            model_name='uploadfile',
            name='default_settings',
        ),
        migrations.AddField(
            model_name='datatype',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='datatype',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='datatype',
            name='pandas_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='datatype',
            name='parent',
            field=models.CharField(choices=[('numerical', 'Numerical'), ('temporal', 'Temporal'), ('geographical', 'Geographical'), ('categorical', 'Categorical')], default='categorical', max_length=30),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='file_ext',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='refresh_timeout',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.DeleteModel(
            name='FileSetting',
        ),
    ]
