# Generated by Django 2.2.10 on 2020-06-09 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visualizations', '0005_auto_20200609_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatyperule',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datatyperules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='viztypemark',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viztypemarks', to=settings.AUTH_USER_MODEL),
        ),
    ]
