# Generated by Django 2.2.10 on 2020-06-09 18:00

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0006_auto_20200609_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_history',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_settings',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
