# Generated by Django 2.2.10 on 2020-06-10 10:24

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0008_auto_20200610_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='init_settings',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
