# Generated by Django 2.2.10 on 2020-06-10 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0010_auto_20200610_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datatyperule',
            old_name='formula',
            new_name='rule',
        ),
    ]
