# Generated by Django 2.2.10 on 2020-06-11 22:09

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0011_auto_20200610_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_history',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_settings',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='init_settings',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
