# Generated by Django 2.2.10 on 2020-06-16 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0012_auto_20200612_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatyperule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vizoutput',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='viztypemark',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
