# Generated by Django 2.2.10 on 2020-06-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0013_auto_20200616_0929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datatyperule',
            options={'ordering': ['-created_at'], 'verbose_name': 'DataTypeRule', 'verbose_name_plural': 'DataTypeRules'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='uploadfile',
            options={'ordering': ['-created_at'], 'verbose_name': 'File', 'verbose_name_plural': 'Files'},
        ),
        migrations.AlterModelOptions(
            name='vizoutput',
            options={'ordering': ['-created_at'], 'verbose_name': 'VizOutput', 'verbose_name_plural': 'VizOutputs'},
        ),
        migrations.AlterModelOptions(
            name='viztypemark',
            options={'ordering': ['-created_at'], 'verbose_name': 'VizMarkRule', 'verbose_name_plural': 'VizMarkRules'},
        ),
        migrations.AddField(
            model_name='vizmark',
            name='is_orientation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vizmark',
            name='max_elements',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='vizmark',
            name='sequence',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='vizoutput',
            name='project_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='vizoutput',
            name='viz_code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='viztype',
            name='sequence',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='viztypemark',
            name='project_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='viztypemark',
            name='viz_code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
