# Generated by Django 2.2.10 on 2020-07-02 08:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0014_auto_20200616_1422'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vizmark',
            options={'ordering': ['sequence', 'name'], 'verbose_name': 'VizMark', 'verbose_name_plural': 'VizMarks'},
        ),
        migrations.AlterModelOptions(
            name='viztype',
            options={'ordering': ['sequence', 'name'], 'verbose_name': 'VizType', 'verbose_name_plural': 'VizTypes'},
        ),
        migrations.AddField(
            model_name='datatype',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='updated_at',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='vizmark',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='viztype',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='viztype',
            name='exclude_marks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
