# Generated by Django 2.2.10 on 2020-07-06 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0016_auto_20200706_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='viztypemark',
            name='vizoutput',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viztypemarks', to='visualizations.VizOutput'),
        ),
    ]
