# Generated by Django 2.2.10 on 2020-07-07 10:46

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0017_viztypemark_vizoutput'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viztypemark',
            name='rule',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
