# Generated by Django 2.2.10 on 2020-07-14 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0018_auto_20200707_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
