# Generated by Django 2.2.10 on 2020-07-16 07:52

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0019_feature_is_primary'),
    ]

    operations = [
        migrations.AddField(
            model_name='vizinput',
            name='feature_settings',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='vizoutput',
            name='mark_settings',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
