# Generated by Django 2.2.10 on 2020-07-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0021_vizoutput_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vizoutput',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=5, null=True),
        ),
    ]
