# Generated by Django 2.2.10 on 2020-07-28 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0023_vizmark_is_grouping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viztype',
            old_name='exclude_marks',
            new_name='include_marks',
        ),
    ]
