# Generated by Django 2.2.10 on 2020-08-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0025_feature_apply_onlyto_viz'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'ordering': ['sequence'], 'verbose_name': 'Feature', 'verbose_name_plural': 'Features'},
        ),
        migrations.AddField(
            model_name='feature',
            name='sequence',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
