# Generated by Django 2.2.10 on 2020-08-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0026_auto_20200805_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='vizoutput',
            name='mark_settings_str',
            field=models.TextField(blank=True, null=True),
        ),
    ]
