# Generated by Django 2.2.10 on 2020-10-06 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0029_project_dash_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='address_ip',
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
    ]
