# Generated by Django 2.2.10 on 2020-11-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0030_project_address_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='VizGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'VizGoal',
                'verbose_name_plural': 'VizGoals',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='viztype',
            name='code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='viztype',
            name='include_goals',
            field=models.TextField(blank=True, null=True),
        ),
    ]
