# Generated by Django 2.2.10 on 2020-11-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0032_auto_20201110_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viztype',
            name='include_goals',
        ),
        migrations.AddField(
            model_name='vizgoal',
            name='viz_types',
            field=models.TextField(blank=True, null=True),
        ),
    ]
