# Generated by Django 2.2.10 on 2020-11-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0033_auto_20201110_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='has_vizs',
            field=models.BooleanField(default=False),
        ),
    ]
