# Generated by Django 2.2.10 on 2021-02-09 11:27

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0035_auto_20210208_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformPortal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('more_details', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PlatformPortal',
                'verbose_name_plural': 'PlatformPortals',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='dataportal',
            name='platform',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dataportals', to='visualizations.PlatformPortal'),
            preserve_default=False,
        ),
    ]
