# Generated by Django 2.2.10 on 2021-02-10 17:06

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0036_auto_20210209_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='more_details',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
