# Generated by Django 2.2.10 on 2021-02-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0037_uploadfile_more_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='related_files',
            field=models.ManyToManyField(blank=True, related_name='_uploadfile_related_files_+', to='visualizations.UploadFile'),
        ),
    ]
