# Generated by Django 2.2.10 on 2021-02-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0038_uploadfile_related_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatyperule',
            name='address_ip',
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
    ]
