# Generated by Django 2.2.10 on 2021-02-14 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0039_datatyperule_address_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='from_query',
            field=models.BooleanField(default=False),
        ),
    ]
