# Generated by Django 2.2.10 on 2021-02-25 13:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0040_uploadfile_from_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatyperule',
            name='update_date',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='datatyperule',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
