# Generated by Django 2.2.10 on 2021-02-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0041_auto_20210225_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatyperule',
            name='update_date',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
