# Generated by Django 2.2.10 on 2021-02-25 13:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0042_auto_20210225_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatyperule',
            name='update_date',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='datatyperule',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
