# Generated by Django 2.2.10 on 2021-03-11 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0044_auto_20210310_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfile',
            name='updated_at',
        ),
    ]
