# Generated by Django 2.2.10 on 2021-03-11 22:20

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0045_remove_uploadfile_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='updated_at',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
