# Generated by Django 2.2.10 on 2021-06-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0047_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
