# Generated by Django 2.2.10 on 2021-06-30 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0048_feedback_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='themes/')),
                ('sequence', models.IntegerField(blank=True, default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Theme',
                'verbose_name_plural': 'Themes',
                'ordering': ['sequence', 'name'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('internal', 'Internal'), ('external', 'External'), ('proposed', 'Proposed')], default='internal', max_length=30),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='related_projects',
            field=models.ManyToManyField(blank=True, related_name='related_projects', to='visualizations.Project'),
        ),
        migrations.AddField(
            model_name='project',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='themes', to='visualizations.Theme'),
        ),
    ]
