# Generated by Django 2.2.10 on 2021-07-01 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0049_auto_20210630_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
