# Generated by Django 2.2.10 on 2021-08-01 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0050_project_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='feedback_type',
            field=models.CharField(choices=[('general', 'General'), ('status', 'Project Status'), ('data', 'Data Issue')], default='general', max_length=30),
        ),
        migrations.AddField(
            model_name='feedback',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='visualizations.UploadFile'),
        ),
        migrations.AddField(
            model_name='project',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='is_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploadfiles', to='visualizations.Theme'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='visualizations.Project'),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='file_link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attach', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('feedback', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='visualizations.Feedback')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='visualizations.Project')),
            ],
            options={
                'verbose_name': 'Attachment',
                'verbose_name_plural': 'Attachments',
            },
        ),
    ]
