# Generated by Django 2.2.10 on 2021-08-01 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0052_auto_20210801_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='state',
        ),
    ]
