# Generated by Django 2.2.10 on 2021-08-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0053_remove_project_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
