# Generated by Django 2.2.10 on 2021-08-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0055_auto_20210827_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='user_request_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
