# Generated by Django 2.2.10 on 2021-09-24 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0056_auto_20210828_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('sequence', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'verbose_name': 'ProjectStatus',
                'verbose_name_plural': 'ProjectStatuses',
                'ordering': ['sequence', 'name'],
            },
        ),
        migrations.AddField(
            model_name='feedback',
            name='user_type',
            field=models.CharField(choices=[('non-expert', 'Citizen'), ('intermediate', 'Publisher'), ('expert', 'Developer')], default='non-expert', max_length=30),
        ),
        migrations.AddField(
            model_name='project',
            name='Status_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='has_new_comment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='last_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='last_general_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='nb_comments',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='has_new_comment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='last_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='last_general_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='nb_comments',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='datatyperule',
            name='user_type',
            field=models.CharField(choices=[('non-expert', 'Citizen'), ('intermediate', 'Publisher'), ('expert', 'Developer')], default='non-expert', max_length=30),
        ),
        migrations.AlterField(
            model_name='vizoutput',
            name='user_type',
            field=models.CharField(choices=[('non-expert', 'Citizen'), ('intermediate', 'Publisher'), ('expert', 'Developer')], default='non-expert', max_length=30),
        ),
        migrations.AlterField(
            model_name='viztypemark',
            name='user_type',
            field=models.CharField(choices=[('non-expert', 'Citizen'), ('intermediate', 'Publisher'), ('expert', 'Developer')], default='non-expert', max_length=30),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statuses', to='visualizations.ProjectStatus'),
        ),
    ]
