# Generated by Django 2.2.10 on 2021-09-24 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0057_auto_20210924_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribeDataArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'SubscribeDataArea',
                'verbose_name_plural': 'SubscribeDataAreas',
            },
        ),
        migrations.CreateModel(
            name='SubscribeDataProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscribes', to='visualizations.UploadFile')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscribes', to='visualizations.Project')),
            ],
            options={
                'verbose_name': 'SubscribeDataProject',
                'verbose_name_plural': 'SubscribeDataProjects',
            },
        ),
    ]
