# Generated by Django 2.2.10 on 2021-09-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0058_subscribedataarea_subscribedataproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='data_provided',
            field=models.BooleanField(default=True),
        ),
    ]
