# Generated by Django 2.2.10 on 2021-09-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0059_uploadfile_data_provided'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstatus',
            name='for_existing_project',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectstatus',
            name='for_suggested_project',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectstatus',
            name='for_update_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_type',
            field=models.CharField(choices=[('general', 'General'), ('status', 'Project Status'), ('data', 'Data Issue'), ('requirement', 'Requirement Clarification')], default='general', max_length=30),
        ),
    ]
