# Generated by Django 2.2.10 on 2021-10-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0061_projectstatus_abbreviation'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstatus',
            name='name_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='projectstatus',
            name='name_fr',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='name_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='name_fr',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
