# Generated by Django 2.2.10 on 2021-10-09 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0063_auto_20211008_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='developed_internally',
            field=models.BooleanField(default=False),
        ),
    ]
