# Generated by Django 2.2.10 on 2021-10-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0064_project_developed_internally'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstatus',
            name='color',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='projectstatus',
            name='icon',
            field=models.CharField(default='', max_length=20),
        ),
    ]
