# Generated by Django 2.2.10 on 2021-10-23 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0065_auto_20211023_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstatus',
            name='bg_color',
            field=models.CharField(default='', max_length=10),
        ),
    ]
