# Generated by Django 2.2.10 on 2021-10-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0066_projectstatus_bg_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='action_type',
            field=models.CharField(choices=[('like', 'Like'), ('favorite', 'Favorite')], default='like', max_length=30),
        ),
        migrations.AddField(
            model_name='project',
            name='nb_favorites',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='nb_favorites',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
