# Generated by Django 2.2.10 on 2021-10-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0067_auto_20211030_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_popular',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='is_popular',
            field=models.BooleanField(default=True),
        ),
    ]
