# Generated by Django 2.2.10 on 2021-10-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0068_auto_20211030_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfile',
            name='is_popular',
        ),
        migrations.AddField(
            model_name='theme',
            name='is_popular',
            field=models.BooleanField(default=True),
        ),
    ]
