# Generated by Django 2.2.10 on 2021-11-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0070_auto_20211031_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
