# Generated by Django 2.2.10 on 2021-11-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0072_auto_20211116_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Status_history',
            new_name='status_history',
        ),
        migrations.AddField(
            model_name='project',
            name='list_datasets',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sequence_mobile',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.DeleteModel(
            name='Tool',
        ),
    ]
