# Generated by Django 2.2.10 on 2021-11-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0073_auto_20211121_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='static_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
