# Generated by Django 2.2.10 on 2022-04-08 09:35

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visualizations', '0074_project_static_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, editable=False, max_length=8)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('transproject_settings', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('shared', models.BooleanField(default=False)),
                ('has_projects', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transprojects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TransProject',
                'verbose_name_plural': 'TransProjects',
                'ordering': ['-created_at'],
            },
        ),
    ]
