# Generated by Django 2.2.10 on 2021-02-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('expert', 'Confident'), ('intermediate', 'Less confident'), ('non-expert', 'Not confident')], default='non-expert', max_length=30),
        ),
    ]
